name: Auto Trigger Keep Codespace Active
on:
  repository_dispatch:
    types: [auto-trigger]
  workflow_dispatch: # Manual trigger for testing
jobs:
  dispatch-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq
          echo "GitHub CLI version:"
          gh --version
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.CODESPACE_PAT }}" | gh auth login --with-token
          gh auth status
      - name: Run Dispatch Loop
        run: |
          # Max job duration ~6 hours (21,000 seconds)
          MAX_DURATION=400
          # Interval between dispatches: 40 minutes (2400 seconds)
          INTERVAL=18000
          # Start time
          START_TIME=$(date +%s)
          
          while true; do
            CURRENT_TIME=$(date +%s)
            ELAPSED=$((CURRENT_TIME - START_TIME))
            
            # Check if nearing 6-hour limit (leave 300s buffer)
            if [ $ELAPSED -gt $((MAX_DURATION - 300)) ]; then
              echo "Nearing 6-hour limit. Triggering self-restart..."
              echo '{"event_type": "auto-trigger"}' > self_dispatch.json
              gh api -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                /repos/${{ github.repository }}/dispatches \
                --input self_dispatch.json
              echo "Self-restart dispatched. Exiting."
              exit 0
            fi
            
            # Check API rate limit
            RATE_LIMIT=$(gh api /rate_limit --jq '.resources.core.remaining')
            echo "API rate limit remaining: $RATE_LIMIT"
            if [ "$RATE_LIMIT" -lt 10 ]; then
              echo "Rate limit too low. Waiting 300 seconds..."
              sleep 300
              continue
            fi
            
            # Dispatch keep-codespace-active event
            echo "Dispatching keep-codespace-active at $(date -u '+%Y-%m-%d %H:%M:%S UTC')..."
            echo '{"event_type": "keep-codespace-active"}' > dispatch.json
            
            RETRIES=3
            ATTEMPT=1
            until [ $ATTEMPT -gt $RETRIES ]; do
              echo "Dispatch attempt $ATTEMPT of $RETRIES..."
              DISPATCH_OUTPUT=$(gh api -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                /repos/${{ github.repository }}/dispatches \
                --input dispatch.json 2>&1)
              DISPATCH_STATUS=$?
              if [ $DISPATCH_STATUS -eq 0 ]; then
                echo "Successfully dispatched keep-codespace-active."
                break
              fi
              echo "Failed to dispatch (Attempt $ATTEMPT/$RETRIES). Error: $DISPATCH_OUTPUT"
              if [ $ATTEMPT -lt $RETRIES ]; then
                echo "Retrying in 60 seconds..."
                sleep 60
              fi
              ATTEMPT=$((ATTEMPT + 1))
            done
            
            if [ $DISPATCH_STATUS -ne 0 ]; then
              echo "Error: Failed to dispatch after $RETRIES attempts."
              exit 1
            fi
            
            # Sleep for the interval
            echo "Sleeping for $INTERVAL seconds..."
            sleep $INTERVAL
          done
